// Pending offline invoices — list view + reprint action.
//
// Surfaces every row in offline_invoices where sync_status='pending'
// so the cashier can:
//   - see at a glance how many sales are queued to push to the cloud
//   - reprint any one of them (e.g. printer jammed mid-checkout, or
//     customer asks for a duplicate)
//
// Reprint rehydrates the original payload_json + qr_base64 from SQLite
// and re-runs the same printReceipt() pipeline used at checkout — so the
// reprinted slip is byte-identical to the original.
//
// What this is NOT:
//   - a sync push (Step 11) — pending stays pending until /api/sync/push
//   - a delete/void action — voiding a saved sale is an audit event and
//     needs its own paper trail; deliberately omitted here.

import { useCallback, useEffect, useState } from "react";
import {
  listPendingInvoices,
  getOfflineInvoice,
  type PendingInvoice,
  type OfflineInvoicePayload,
} from "../lib/invoices";
import { printReceipt, type ReceiptLine } from "../lib/peripherals";

const LS_PRINTER = "pos_desktop_peripherals_printer";

type Props = { companyName?: string; vatNumber?: string };

export default function PendingInvoices({
  companyName = "ZACOD POS",
  vatNumber = "300000000000003",
}: Props) {
  const [rows, setRows] = useState<PendingInvoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);
  const [reprintingId, setReprintingId] = useState<number | null>(null);
  const [toast, setToast] = useState<{ kind: "ok" | "err"; text: string } | null>(null);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const r = await listPendingInvoices();
      setRows(r);
      setErr(null);
    } catch (e: any) {
      setErr(e?.message ?? "تعذّر تحميل القائمة");
    } finally {
      setLoading(false);
    }
  }, []);

  // Runtime guard — payload_json is written by SalesScreen but could be from
  // an older app version with a different shape, or get corrupted on disk.
  // Fail loudly with a clear toast instead of crashing inside the print loop.
  function isValidPayload(x: unknown): x is OfflineInvoicePayload {
    if (!x || typeof x !== "object") return false;
    const p = x as any;
    return (
      Array.isArray(p.lines) &&
      p.lines.every((l: any) =>
        l && typeof l.nameAr === "string" &&
        typeof l.qty === "number" && typeof l.unitPrice === "number"
      ) &&
      typeof p.subtotal === "number" &&
      typeof p.vat === "number" &&
      typeof p.grandTotal === "number" &&
      typeof p.timestamp === "string" &&
      (p.paymentMethod === "cash" || p.paymentMethod === "card")
    );
  }

  useEffect(() => { void refresh(); }, [refresh]);

  async function reprint(row: PendingInvoice) {
    const printer = localStorage.getItem(LS_PRINTER);
    if (!printer) {
      setToast({ kind: "err", text: "لم يتم تكوين طابعة. افتح ‹الأجهزة الطرفية› أولاً." });
      return;
    }
    setReprintingId(row.id);
    setToast(null);
    try {
      const full = await getOfflineInvoice(row.id);
      if (!full) throw new Error("لم يُعثر على الفاتورة");

      // payloadJson was generated by SalesScreen with the OfflineInvoicePayload
      // shape — keep that schema as the contract between save & reprint.
      let parsed: unknown;
      try { parsed = JSON.parse(full.payloadJson); }
      catch { throw new Error("بيانات الفاتورة تالفة (JSON غير صالح)"); }
      if (!isValidPayload(parsed)) {
        throw new Error("بنية الفاتورة غير متوقّعة — قد تكون من إصدار قديم");
      }
      const payload = parsed;

      const body: ReceiptLine[] = [];
      for (const l of payload.lines) {
        const lineTotal = (l.unitPrice * l.qty).toFixed(2);
        body.push({ text: `${l.nameAr.padEnd(20, " ")} ×${l.qty}  ${lineTotal}` });
      }
      body.push({ text: "─".repeat(32) });
      body.push({ text: `المجموع قبل الضريبة:  ${payload.subtotal.toFixed(2)}` });
      body.push({ text: `ضريبة القيمة المضافة: ${payload.vat.toFixed(2)}` });
      body.push({ text: `الإجمالي:             ${payload.grandTotal.toFixed(2)}`, bold: true });
      body.push({ text: `طريقة الدفع: ${payload.paymentMethod === "cash" ? "نقداً" : "بطاقة"}` });

      await printReceipt({
        printerName: printer,
        header: [
          { text: companyName, bold: true, center: true },
          { text: `الرقم الضريبي: ${vatNumber}`, center: true },
          { text: `فاتورة #${full.invoiceNo}`, center: true },
          { text: new Date(payload.timestamp).toLocaleString("ar-SA"), center: true },
          // Reprints are clearly marked so the customer / auditor knows
          // this is a duplicate and not a separate sale.
          { text: "*** نسخة مكررة — REPRINT ***", center: true, bold: true },
        ],
        body,
        footer: [{ text: "شكراً لزيارتكم", center: true }],
        qrData: full.qrBase64 ?? undefined,
        cut: true,
        openDrawer: false, // never kick drawer on a reprint
      });

      setToast({ kind: "ok", text: `✅ أُعيدت طباعة ${full.invoiceNo}` });
    } catch (e: any) {
      setToast({ kind: "err", text: `فشل إعادة الطباعة: ${e?.message ?? e}` });
    } finally {
      setReprintingId(null);
    }
  }

  return (
    <div dir="rtl" style={S.wrap}>
      <div style={S.headerRow}>
        <h2 style={S.h2}>الفواتير المعلّقة ({rows.length})</h2>
        <button onClick={refresh} style={S.refresh} disabled={loading}>
          {loading ? "..." : "🔄 تحديث"}
        </button>
      </div>

      {err && <div style={S.err}>⚠️ {err}</div>}
      {toast && (
        <div style={toast.kind === "ok" ? S.ok : S.err}>{toast.text}</div>
      )}

      {!loading && rows.length === 0 && !err && (
        <div style={S.empty}>لا توجد فواتير معلّقة — كل المبيعات مُزامَنة ✨</div>
      )}

      {rows.length > 0 && (
        <table style={S.table}>
          <thead>
            <tr>
              <th style={S.th}>رقم الفاتورة</th>
              <th style={S.th}>التاريخ</th>
              <th style={S.th}>الحالة</th>
              <th style={S.thRight}>إجراء</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => (
              <tr key={r.id} style={S.tr}>
                <td style={S.tdMono}>{r.invoiceNo}</td>
                <td style={S.td}>{new Date(r.createdAt + "Z").toLocaleString("ar-SA")}</td>
                <td style={S.td}>
                  <span style={S.badge}>{r.syncStatus}</span>
                </td>
                <td style={S.tdRight}>
                  <button
                    onClick={() => reprint(r)}
                    disabled={reprintingId === r.id}
                    style={S.btn}
                  >
                    {reprintingId === r.id ? "..." : "🖨️ إعادة طباعة"}
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

const S = {
  wrap: { maxWidth: 920, margin: "0 auto", width: "100%" } as const,
  headerRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 } as const,
  h2: { margin: 0, fontSize: 18, color: "#0f172a" } as const,
  refresh: { padding: "6px 12px", background: "#fff", border: "1px solid #e2e8f0", borderRadius: 6, cursor: "pointer", fontSize: 13 } as const,
  table: { width: "100%", borderCollapse: "collapse", background: "#fff", border: "1px solid #e2e8f0", borderRadius: 8, overflow: "hidden" } as const,
  th: { textAlign: "right", padding: "10px 12px", background: "#f8fafc", borderBottom: "1px solid #e2e8f0", fontSize: 13, color: "#475569", fontWeight: 600 } as const,
  thRight: { textAlign: "left", padding: "10px 12px", background: "#f8fafc", borderBottom: "1px solid #e2e8f0", fontSize: 13, color: "#475569", fontWeight: 600 } as const,
  tr: { borderBottom: "1px solid #f1f5f9" } as const,
  td: { padding: "10px 12px", fontSize: 14, color: "#0f172a" } as const,
  tdMono: { padding: "10px 12px", fontSize: 13, color: "#0f172a", fontFamily: "ui-monospace, monospace" } as const,
  tdRight: { padding: "10px 12px", textAlign: "left" } as const,
  badge: { display: "inline-block", padding: "2px 8px", background: "#fffbeb", color: "#92400e", border: "1px solid #fde68a", borderRadius: 999, fontSize: 12 } as const,
  btn: { padding: "6px 12px", background: "#2563eb", color: "#fff", border: "none", borderRadius: 6, cursor: "pointer", fontSize: 13, fontWeight: 600 } as const,
  empty: { padding: 40, textAlign: "center", color: "#94a3b8", background: "#fff", border: "1px dashed #e2e8f0", borderRadius: 8 } as const,
  ok: { background: "#f0fdf4", border: "1px solid #bbf7d0", color: "#166534", padding: 12, borderRadius: 6, marginBottom: 12, fontSize: 14 } as const,
  err: { background: "#fef2f2", border: "1px solid #fecaca", color: "#991b1b", padding: 12, borderRadius: 6, marginBottom: 12, fontSize: 14 } as const,
};
