// Standalone activation — Task #199.
//
// User drags & drops (or picks) a .zacolic.json file generated by the cloud
// SuperAdmin. We verify the Ed25519 signature locally against the build's
// pinned public key, then persist it. Then we walk the operator through
// creating the FIRST admin user (only required step on first-run; subsequent
// users are added from the in-app users page).
//
// No network calls. Whole flow runs offline.

import { useEffect, useState } from "react";
import {
  verifyLicenseFile, saveLicense, type SignedLicenseFile, type OfflineLicensePayload,
  createLocalUser, countLocalUsers, DEV_PUBKEY_UNPINNED, PINNED_PUBKEY_FINGERPRINT,
} from "../lib/standalone";
import { getFingerprint } from "../lib/tauri-shim";

type Phase = "intro" | "license-picked" | "license-ok" | "admin-create" | "done";

export default function StandaloneActivation({ onDone, onCancel }: {
  onDone: (payload: OfflineLicensePayload) => void;
  onCancel: () => void;
}) {
  const [phase, setPhase] = useState<Phase>("intro");
  const [file, setFile] = useState<SignedLicenseFile | null>(null);
  const [payload, setPayload] = useState<OfflineLicensePayload | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [fingerprint, setFingerprint] = useState<string>("");
  // Default to true (i.e. assume admin needed) until the async count resolves —
  // this matches the safer "always require admin on first activation" behaviour.
  const [needsAdmin, setNeedsAdmin] = useState<boolean>(true);
  useEffect(() => { void countLocalUsers().then((n) => setNeedsAdmin(n === 0)); }, []);

  // Admin-create form
  const [a, setA] = useState({ username: "admin", displayName: "المسؤول", password: "", password2: "" });
  const [busy, setBusy] = useState(false);

  async function handleFile(f: File) {
    setErr(null);
    try {
      const txt = await f.text();
      const parsed = JSON.parse(txt) as SignedLicenseFile;
      const res = await verifyLicenseFile(parsed);
      if (!res.ok) { setErr(res.error); return; }
      const fp = await getFingerprint();
      setFingerprint(fp);
      // Hardware-bind check
      if (parsed.payload.fingerprintHash) {
        // Compute SHA-256 of the local fingerprint and compare hex
        const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(fp) as BufferSource);
        const hex = Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, "0")).join("");
        if (hex !== parsed.payload.fingerprintHash) {
          setErr(`هذا الترخيص مربوط ببصمة جهاز مختلفة. تواصل مع مزوّد الخدمة لإعادة الإصدار.`);
          return;
        }
      }
      setFile(parsed); setPayload(res.payload); setPhase("license-ok");
    } catch (e: any) {
      setErr(`فشل قراءة الملف: ${e?.message ?? "ملف غير صالح"}`);
    }
  }

  function onPick(e: React.ChangeEvent<HTMLInputElement>) {
    const f = e.target.files?.[0]; if (f) void handleFile(f);
  }
  function onDrop(e: React.DragEvent<HTMLDivElement>) {
    e.preventDefault();
    const f = e.dataTransfer.files?.[0]; if (f) void handleFile(f);
  }

  async function activate() {
    if (!file || !payload) return;
    await saveLicense(file);
    if (needsAdmin) setPhase("admin-create");
    else { setPhase("done"); onDone(payload); }
  }

  async function createAdmin() {
    setErr(null);
    if (a.password !== a.password2) { setErr("كلمتا المرور غير متطابقتين"); return; }
    setBusy(true);
    try {
      await createLocalUser({
        username: a.username, displayName: a.displayName,
        password: a.password, role: "admin",
      });
      setPhase("done");
      if (payload) onDone(payload);
    } catch (e: any) {
      setErr(typeof e === "string" ? e : (e?.message ?? "فشل إنشاء المستخدم"));
    } finally { setBusy(false); }
  }

  return (
    <div dir="rtl" style={S.wrap}>
      <div style={S.card}>
        <header style={S.head}>
          <h1 style={S.title}>تفعيل الوضع المستقل</h1>
          <button onClick={onCancel} style={S.linkBtn}>← العودة لاختيار الوضع</button>
        </header>
        <div style={{ fontSize: 11, color: PINNED_PUBKEY_FINGERPRINT === "EMPTY" ? "#dc2626" : "#16a34a", fontFamily: "monospace", padding: "4px 8px", background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 4, marginBottom: 12, direction: "ltr", textAlign: "left" }}>
          build v{__APP_VERSION__} · pinned pubkey: {PINNED_PUBKEY_FINGERPRINT}
        </div>

        {DEV_PUBKEY_UNPINNED && (
          <div style={S.warn}>
            ⚠️ هذه نسخة تطوير — لم يُضمَّن مفتاح عام مثبّت. التحقق يقبل أي توقيع. في الإنتاج
            عيّن <code>VITE_OFFLINE_LICENSE_PUBLIC_KEY_B64</code> عند البناء.
          </div>
        )}

        {(phase === "intro" || phase === "license-picked") && (
          <div>
            <p style={S.lead}>
              اسحب ملف الترخيص <code>.zacolic.json</code> الذي تسلّمته من مزوّد الخدمة إلى المربع أدناه،
              أو اضغط لاختياره.
            </p>
            <div style={S.drop} onDragOver={(e) => e.preventDefault()} onDrop={onDrop}>
              <div style={{ fontSize: 48, marginBottom: 12 }}>📄</div>
              <div style={{ marginBottom: 12 }}>اسحب الملف هنا، أو</div>
              <label style={S.btnPrimary}>
                اختر ملف
                <input type="file" accept=".json,application/json" onChange={onPick} style={{ display: "none" }} />
              </label>
            </div>
          </div>
        )}

        {phase === "license-ok" && payload && (
          <div>
            <div style={S.success}>✅ تم التحقق من توقيع الترخيص بنجاح</div>
            <div style={S.summary}>
              <KV k="المفتاح" v={payload.licenseKey} mono />
              <KV k="العميل" v={payload.customerName} />
              <KV k="المجال" v={verticalLabel(payload.vertical)} />
              <KV k="الحد الأقصى للمستخدمين" v={String(payload.maxUsers)} />
              <KV k="تاريخ الإصدار" v={new Date(payload.issuedAt).toLocaleDateString("ar-SA")} />
              <KV k="ينتهي في" v={payload.expiresAt ? new Date(payload.expiresAt).toLocaleDateString("ar-SA") : "بدون انتهاء"} />
              <KV k="بصمة الجهاز" v={fingerprint.slice(0, 32) + "…"} mono />
              <KV k="بصمة مفتاح التوقيع" v={file?.publicKeyFingerprint ?? "—"} mono />
            </div>
            <div style={{ display: "flex", gap: 8, marginTop: 16 }}>
              <button onClick={() => { setPhase("intro"); setFile(null); setPayload(null); }} style={S.btnSecondary}>اختيار ملف آخر</button>
              <button onClick={() => void activate()} style={S.btnPrimary}>
                {needsAdmin ? "متابعة → إنشاء مستخدم مسؤول" : "تفعيل وتسجيل دخول"}
              </button>
            </div>
          </div>
        )}

        {phase === "admin-create" && (
          <div>
            <p style={S.lead}>
              أنشئ أول مستخدم مسؤول لإدارة هذا الجهاز. يمكنه لاحقاً إضافة مستخدمين آخرين (كاشير).
            </p>
            <Field label="اسم المستخدم">
              <input value={a.username} onChange={(e) => setA({ ...a, username: e.target.value })} style={S.input} placeholder="admin" />
            </Field>
            <Field label="الاسم الكامل (يظهر في الفواتير)">
              <input value={a.displayName} onChange={(e) => setA({ ...a, displayName: e.target.value })} style={S.input} placeholder="المسؤول" />
            </Field>
            <Field label="كلمة المرور">
              <input type="password" value={a.password} onChange={(e) => setA({ ...a, password: e.target.value })} style={S.input} />
            </Field>
            <Field label="تأكيد كلمة المرور">
              <input type="password" value={a.password2} onChange={(e) => setA({ ...a, password2: e.target.value })} style={S.input} />
            </Field>
            <button onClick={createAdmin} disabled={busy || !a.password} style={S.btnPrimary}>
              {busy ? "جارٍ الإنشاء…" : "إنشاء المستخدم وتسجيل الدخول"}
            </button>
          </div>
        )}

        {err && <div style={{ ...S.err, whiteSpace: "pre-wrap" }}>⚠️ {err}</div>}
      </div>
    </div>
  );
}

function verticalLabel(v: string): string {
  return ({ retail: "تجزئة عامة", grocery: "بقالة/سوبرماركت", pharmacy: "صيدلية", restaurant: "مطعم" } as Record<string, string>)[v] ?? v;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label style={{ display: "block", marginBottom: 12 }}>
    <div style={{ marginBottom: 4, fontSize: 13, fontWeight: 600 }}>{label}</div>
    {children}
  </label>;
}
function KV({ k, v, mono }: { k: string; v: string; mono?: boolean }) {
  return <div style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid #f1f5f9" }}>
    <span style={{ color: "#64748b" }}>{k}</span>
    <span style={{ fontFamily: mono ? "ui-monospace, monospace" : undefined, fontSize: mono ? 12 : 14 }}>{v}</span>
  </div>;
}

const S = {
  wrap: { minHeight: "100vh", background: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)", display: "flex", alignItems: "center", justifyContent: "center", padding: 24, fontFamily: "'Segoe UI', system-ui, sans-serif" } as const,
  card: { maxWidth: 640, width: "100%", background: "#fff", borderRadius: 16, padding: 28, boxShadow: "0 20px 60px rgba(0,0,0,.3)" } as const,
  head: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16, paddingBottom: 12, borderBottom: "1px solid #e2e8f0" } as const,
  title: { margin: 0, fontSize: 20, color: "#0f172a" } as const,
  linkBtn: { background: "none", border: "none", color: "#2563eb", cursor: "pointer", fontFamily: "inherit", fontSize: 13 } as const,
  lead: { fontSize: 14, lineHeight: 1.7, color: "#334155", marginBottom: 16 } as const,
  drop: { border: "2px dashed #cbd5e1", borderRadius: 12, padding: 40, textAlign: "center" as const, background: "#f8fafc", color: "#475569" } as const,
  btnPrimary: { display: "inline-block", padding: "10px 20px", background: "#2563eb", color: "#fff", border: "none", borderRadius: 8, cursor: "pointer", fontFamily: "inherit", fontSize: 14, fontWeight: 600 } as const,
  btnSecondary: { padding: "10px 20px", background: "#f1f5f9", color: "#0f172a", border: "1px solid #cbd5e1", borderRadius: 8, cursor: "pointer", fontFamily: "inherit", fontSize: 14 } as const,
  success: { padding: 12, background: "#f0fdf4", color: "#166534", border: "1px solid #bbf7d0", borderRadius: 8, marginBottom: 16, fontSize: 14 } as const,
  warn: { padding: 10, background: "#fffbeb", color: "#92400e", border: "1px solid #fde68a", borderRadius: 8, marginBottom: 16, fontSize: 13 } as const,
  err: { padding: 12, background: "#fef2f2", color: "#991b1b", border: "1px solid #fecaca", borderRadius: 8, marginTop: 12, fontSize: 14 } as const,
  summary: { background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 8, padding: 16 } as const,
  input: { width: "100%", padding: "10px 12px", border: "1px solid #cbd5e1", borderRadius: 6, fontSize: 14, boxSizing: "border-box" } as const,
};
