// Auto-generated from قالب-دليل-الحسابات-commercial template.
// Used to seed a brand-new tenant with a complete commercial chart of accounts.

export type DefaultCoaRow = {
  code: string;
  nameAr: string;
  nameEn: string | null;
  accountType: "asset" | "liability" | "equity" | "revenue" | "expense";
  parentCode: string | null;
  level: number;
  isPosting: boolean;
  isActive: boolean;
  reportDirection: string | null;
};

export const DEFAULT_CHART_OF_ACCOUNTS: DefaultCoaRow[] = [
  {
    "code": "1",
    "nameAr": "الأصول",
    "nameEn": "ASSETS",
    "accountType": "asset",
    "parentCode": null,
    "level": 1,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11",
    "nameAr": "الأصول المتداولة",
    "nameEn": "Current Assets",
    "accountType": "asset",
    "parentCode": "1",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1101",
    "nameAr": "النقدية وما في حكمها",
    "nameEn": "Cash and Cash Equivalents",
    "accountType": "asset",
    "parentCode": "11",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1102",
    "nameAr": "البنوك",
    "nameEn": "Banks",
    "accountType": "asset",
    "parentCode": "11",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1103",
    "nameAr": "العملاء والذمم المدينة",
    "nameEn": "Accounts Receivable",
    "accountType": "asset",
    "parentCode": "11",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1104",
    "nameAr": "أوراق القبض",
    "nameEn": "Notes Receivable",
    "accountType": "asset",
    "parentCode": "11",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1105",
    "nameAr": "المخزون",
    "nameEn": "Inventory",
    "accountType": "asset",
    "parentCode": "11",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1106",
    "nameAr": "المصروفات المدفوعة مقدماً",
    "nameEn": "Prepaid Expenses",
    "accountType": "asset",
    "parentCode": "11",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1107",
    "nameAr": "ضريبة القيمة المضافة المدخلة",
    "nameEn": "VAT Receivable (Input)",
    "accountType": "asset",
    "parentCode": "11",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1108",
    "nameAr": "أرصدة مدينة أخرى",
    "nameEn": "Other Receivables",
    "accountType": "asset",
    "parentCode": "11",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1109",
    "nameAr": "وسيط استلام البضاعة",
    "nameEn": "Goods Receiving Clearing",
    "accountType": "asset",
    "parentCode": "11",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "12",
    "nameAr": "الأصول غير المتداولة",
    "nameEn": "Non-current Assets",
    "accountType": "asset",
    "parentCode": "1",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1201",
    "nameAr": "الأصول الثابتة",
    "nameEn": "Property, Plant & Equipment",
    "accountType": "asset",
    "parentCode": "12",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1202",
    "nameAr": "مجمع الإهلاك",
    "nameEn": "Accumulated Depreciation",
    "accountType": "asset",
    "parentCode": "12",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "1203",
    "nameAr": "الأصول غير الملموسة",
    "nameEn": "Intangible Assets",
    "accountType": "asset",
    "parentCode": "12",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2",
    "nameAr": "الخصوم",
    "nameEn": "LIABILITIES",
    "accountType": "liability",
    "parentCode": null,
    "level": 1,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "21",
    "nameAr": "الخصوم المتداولة",
    "nameEn": "Current Liabilities",
    "accountType": "liability",
    "parentCode": "2",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2101",
    "nameAr": "الموردون والذمم الدائنة",
    "nameEn": "Accounts Payable",
    "accountType": "liability",
    "parentCode": "21",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2102",
    "nameAr": "أوراق الدفع",
    "nameEn": "Notes Payable",
    "accountType": "liability",
    "parentCode": "21",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2103",
    "nameAr": "قروض قصيرة الأجل",
    "nameEn": "Short-term Loans",
    "accountType": "liability",
    "parentCode": "21",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2104",
    "nameAr": "ضريبة القيمة المضافة المستحقة",
    "nameEn": "VAT Payable (Output)",
    "accountType": "liability",
    "parentCode": "21",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2105",
    "nameAr": "الرواتب والأجور المستحقة",
    "nameEn": "Salaries Payable",
    "accountType": "liability",
    "parentCode": "21",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2106",
    "nameAr": "الزكاة وضريبة الدخل المستحقة",
    "nameEn": "Zakat & Income Tax Payable",
    "accountType": "liability",
    "parentCode": "21",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2107",
    "nameAr": "مصروفات مستحقة",
    "nameEn": "Accrued Expenses",
    "accountType": "liability",
    "parentCode": "21",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2108",
    "nameAr": "أرصدة دائنة أخرى",
    "nameEn": "Other Payables",
    "accountType": "liability",
    "parentCode": "21",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "22",
    "nameAr": "الخصوم غير المتداولة",
    "nameEn": "Non-current Liabilities",
    "accountType": "liability",
    "parentCode": "2",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2201",
    "nameAr": "قروض طويلة الأجل",
    "nameEn": "Long-term Loans",
    "accountType": "liability",
    "parentCode": "22",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "2202",
    "nameAr": "مخصص مكافأة نهاية الخدمة",
    "nameEn": "End-of-Service Provision",
    "accountType": "liability",
    "parentCode": "22",
    "level": 3,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "3",
    "nameAr": "حقوق الملكية",
    "nameEn": "EQUITY",
    "accountType": "equity",
    "parentCode": null,
    "level": 1,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "31",
    "nameAr": "رأس المال",
    "nameEn": "Capital",
    "accountType": "equity",
    "parentCode": "3",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "32",
    "nameAr": "الاحتياطيات",
    "nameEn": "Reserves",
    "accountType": "equity",
    "parentCode": "3",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "33",
    "nameAr": "الأرباح المرحّلة",
    "nameEn": "Retained Earnings",
    "accountType": "equity",
    "parentCode": "3",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "34",
    "nameAr": "أرباح / خسائر العام الحالي",
    "nameEn": "Current Year P&L",
    "accountType": "equity",
    "parentCode": "3",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "35",
    "nameAr": "السحب الشخصي",
    "nameEn": "Owner Drawings",
    "accountType": "equity",
    "parentCode": "3",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11011",
    "nameAr": "الصندوق الرئيسي",
    "nameEn": "Main Cash",
    "accountType": "asset",
    "parentCode": "1101",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11012",
    "nameAr": "صندوق المبيعات",
    "nameEn": "Sales Cash",
    "accountType": "asset",
    "parentCode": "1101",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11021",
    "nameAr": "البنك الأهلي السعودي",
    "nameEn": "SNB Bank",
    "accountType": "asset",
    "parentCode": "1102",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11022",
    "nameAr": "بنك الراجحي",
    "nameEn": "Al Rajhi Bank",
    "accountType": "asset",
    "parentCode": "1102",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11031",
    "nameAr": "العملاء — محليون",
    "nameEn": "Local Customers",
    "accountType": "asset",
    "parentCode": "1103",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11032",
    "nameAr": "العملاء — تصدير",
    "nameEn": "Export Customers",
    "accountType": "asset",
    "parentCode": "1103",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11033",
    "nameAr": "مخصص الديون المشكوك فيها",
    "nameEn": "Allowance for Doubtful Debts",
    "accountType": "asset",
    "parentCode": "1103",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11051",
    "nameAr": "مخزون البضاعة",
    "nameEn": "Merchandise Inventory",
    "accountType": "asset",
    "parentCode": "1105",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11071",
    "nameAr": "ضريبة القيمة المضافة — مشتريات",
    "nameEn": "VAT Input on Purchases",
    "accountType": "asset",
    "parentCode": "1107",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11091",
    "nameAr": "وسيط الاستلام",
    "nameEn": "Receiving Clearing",
    "accountType": "asset",
    "parentCode": "1109",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "12011",
    "nameAr": "أراضي ومباني",
    "nameEn": "Land & Buildings",
    "accountType": "asset",
    "parentCode": "1201",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "12012",
    "nameAr": "أثاث ومعدات مكتبية",
    "nameEn": "Furniture & Office Equipment",
    "accountType": "asset",
    "parentCode": "1201",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "12013",
    "nameAr": "أجهزة حاسب آلي",
    "nameEn": "Computers",
    "accountType": "asset",
    "parentCode": "1201",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "12014",
    "nameAr": "وسائل نقل",
    "nameEn": "Vehicles",
    "accountType": "asset",
    "parentCode": "1201",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "12021",
    "nameAr": "مجمع إهلاك المباني",
    "nameEn": "Acc. Depreciation — Buildings",
    "accountType": "asset",
    "parentCode": "1202",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "12022",
    "nameAr": "مجمع إهلاك الأثاث",
    "nameEn": "Acc. Depreciation — Furniture",
    "accountType": "asset",
    "parentCode": "1202",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "12023",
    "nameAr": "مجمع إهلاك الحاسب الآلي",
    "nameEn": "Acc. Depreciation — Computers",
    "accountType": "asset",
    "parentCode": "1202",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "12024",
    "nameAr": "مجمع إهلاك السيارات",
    "nameEn": "Acc. Depreciation — Vehicles",
    "accountType": "asset",
    "parentCode": "1202",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "21011",
    "nameAr": "موردون محليون",
    "nameEn": "Local Suppliers",
    "accountType": "liability",
    "parentCode": "2101",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "21012",
    "nameAr": "موردون أجانب",
    "nameEn": "Foreign Suppliers",
    "accountType": "liability",
    "parentCode": "2101",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "21041",
    "nameAr": "ضريبة القيمة المضافة — مبيعات",
    "nameEn": "VAT Output on Sales",
    "accountType": "liability",
    "parentCode": "2104",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "21051",
    "nameAr": "رواتب وأجور مستحقة",
    "nameEn": "Salaries Accrued",
    "accountType": "liability",
    "parentCode": "2105",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "3101",
    "nameAr": "رأس المال المدفوع",
    "nameEn": "Paid-in Capital",
    "accountType": "equity",
    "parentCode": "31",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "3201",
    "nameAr": "احتياطي نظامي",
    "nameEn": "Statutory Reserve",
    "accountType": "equity",
    "parentCode": "32",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "3301",
    "nameAr": "أرباح مرحّلة من سنوات سابقة",
    "nameEn": "Retained Earnings — Prior",
    "accountType": "equity",
    "parentCode": "33",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "3401",
    "nameAr": "صافي الربح / الخسارة للسنة",
    "nameEn": "Net Income / Loss",
    "accountType": "equity",
    "parentCode": "34",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "4",
    "nameAr": "الإيرادات",
    "nameEn": "REVENUE",
    "accountType": "revenue",
    "parentCode": null,
    "level": 1,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "41",
    "nameAr": "إيرادات النشاط الرئيسي",
    "nameEn": "Operating Revenue",
    "accountType": "revenue",
    "parentCode": "4",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "4101",
    "nameAr": "مبيعات",
    "nameEn": "Sales",
    "accountType": "revenue",
    "parentCode": "41",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "4102",
    "nameAr": "مردودات المبيعات",
    "nameEn": "Sales Returns",
    "accountType": "revenue",
    "parentCode": "41",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "4103",
    "nameAr": "خصم مكتسب",
    "nameEn": "Discount Earned",
    "accountType": "revenue",
    "parentCode": "41",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "42",
    "nameAr": "إيرادات أخرى",
    "nameEn": "Other Revenue",
    "accountType": "revenue",
    "parentCode": "4",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "4201",
    "nameAr": "أرباح بيع أصول",
    "nameEn": "Gain on Sale of Assets",
    "accountType": "revenue",
    "parentCode": "42",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "4202",
    "nameAr": "إيرادات متنوعة",
    "nameEn": "Miscellaneous Revenue",
    "accountType": "revenue",
    "parentCode": "42",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5",
    "nameAr": "المصروفات",
    "nameEn": "EXPENSES",
    "accountType": "expense",
    "parentCode": null,
    "level": 1,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "51",
    "nameAr": "تكلفة المبيعات",
    "nameEn": "Cost of Goods Sold",
    "accountType": "expense",
    "parentCode": "5",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5101",
    "nameAr": "تكلفة البضاعة المباعة",
    "nameEn": "COGS",
    "accountType": "expense",
    "parentCode": "51",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5102",
    "nameAr": "مردودات المشتريات",
    "nameEn": "Purchase Returns",
    "accountType": "expense",
    "parentCode": "51",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5103",
    "nameAr": "خصم ممنوح",
    "nameEn": "Discount Allowed",
    "accountType": "expense",
    "parentCode": "51",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "52",
    "nameAr": "المصروفات الإدارية والعمومية",
    "nameEn": "G&A Expenses",
    "accountType": "expense",
    "parentCode": "5",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5201",
    "nameAr": "رواتب وأجور",
    "nameEn": "Salaries & Wages",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5202",
    "nameAr": "بدلات وحوافز",
    "nameEn": "Allowances & Bonuses",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5203",
    "nameAr": "تأمينات اجتماعية",
    "nameEn": "Social Insurance (GOSI)",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5204",
    "nameAr": "إيجارات",
    "nameEn": "Rent",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5205",
    "nameAr": "كهرباء وماء",
    "nameEn": "Utilities",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5206",
    "nameAr": "اتصالات وإنترنت",
    "nameEn": "Communications",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5207",
    "nameAr": "قرطاسية ومطبوعات",
    "nameEn": "Stationery & Printing",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5208",
    "nameAr": "صيانة وإصلاحات",
    "nameEn": "Maintenance & Repairs",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5209",
    "nameAr": "ضيافة وحفلات",
    "nameEn": "Hospitality",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5210",
    "nameAr": "أتعاب مهنية واستشارات",
    "nameEn": "Professional Fees",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5211",
    "nameAr": "اشتراكات ورسوم حكومية",
    "nameEn": "Government Fees",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5212",
    "nameAr": "مصروفات بنكية",
    "nameEn": "Bank Charges",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5215",
    "nameAr": "مكافأة نهاية الخدمة",
    "nameEn": "End-of-Service Expense",
    "accountType": "expense",
    "parentCode": "52",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "21051",
    "nameAr": "صافي الرواتب المستحقة الدفع",
    "nameEn": "Net Salaries Payable",
    "accountType": "liability",
    "parentCode": "2105",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "21052",
    "nameAr": "تأمينات اجتماعية مستحقة الدفع",
    "nameEn": "GOSI Payable",
    "accountType": "liability",
    "parentCode": "2105",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "21053",
    "nameAr": "استقطاعات أخرى مستحقة الدفع",
    "nameEn": "Other Deductions Payable",
    "accountType": "liability",
    "parentCode": "2105",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "11081",
    "nameAr": "سلف وعُهد الموظفين",
    "nameEn": "Loans & Advances to Employees",
    "accountType": "asset",
    "parentCode": "1108",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "22021",
    "nameAr": "مخصص مكافأة نهاية الخدمة",
    "nameEn": "EOS Provision",
    "accountType": "liability",
    "parentCode": "2202",
    "level": 4,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "balance_sheet"
  },
  {
    "code": "53",
    "nameAr": "مصروفات البيع والتسويق",
    "nameEn": "Selling & Marketing",
    "accountType": "expense",
    "parentCode": "5",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5301",
    "nameAr": "دعاية وإعلان",
    "nameEn": "Advertising",
    "accountType": "expense",
    "parentCode": "53",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5302",
    "nameAr": "عمولات مبيعات",
    "nameEn": "Sales Commissions",
    "accountType": "expense",
    "parentCode": "53",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5303",
    "nameAr": "نقل وشحن مبيعات",
    "nameEn": "Freight Out",
    "accountType": "expense",
    "parentCode": "53",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "54",
    "nameAr": "الإهلاكات",
    "nameEn": "Depreciation",
    "accountType": "expense",
    "parentCode": "5",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5401",
    "nameAr": "إهلاك الأصول الثابتة",
    "nameEn": "Depreciation Expense",
    "accountType": "expense",
    "parentCode": "54",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5402",
    "nameAr": "إطفاء الأصول غير الملموسة",
    "nameEn": "Amortization Expense",
    "accountType": "expense",
    "parentCode": "54",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "55",
    "nameAr": "مصروفات أخرى",
    "nameEn": "Other Expenses",
    "accountType": "expense",
    "parentCode": "5",
    "level": 2,
    "isPosting": false,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5501",
    "nameAr": "خسائر بيع أصول",
    "nameEn": "Loss on Sale of Assets",
    "accountType": "expense",
    "parentCode": "55",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5502",
    "nameAr": "ديون معدومة",
    "nameEn": "Bad Debts",
    "accountType": "expense",
    "parentCode": "55",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  },
  {
    "code": "5503",
    "nameAr": "غرامات وجزاءات",
    "nameEn": "Fines & Penalties",
    "accountType": "expense",
    "parentCode": "55",
    "level": 3,
    "isPosting": true,
    "isActive": true,
    "reportDirection": "income_statement"
  }
];
