import { Router, type IRouter } from "express";
import healthRouter from "./health";
import companiesRouter from "./companies";
import customersRouter from "./customers";
import invoicesRouter from "./invoices";
import dashboardRouter from "./dashboard";
import deviceInfoRouter from "./device-info";
import zatcaRouter from "./zatca";
import authRouter from "./auth";
import suppliersRouter from "./suppliers";
import adminRouter from "./admin";
import reportsRouter from "./reports";
import inventoryRouter from "./inventory";
import accountsRouter from "./accounts";
import branchesRouter from "./branches";
import journalEntriesRouter from "./journalEntries";
import currenciesRouter from "./currencies";
import accountingReportsRouter from "./reports-accounting";
import purchasingRouter from "./purchasing";
import salesRouter from "./sales";
import salesAnalyticsRouter from "./sales-analytics";
import purchasesAnalyticsRouter from "./purchases-analytics";
import cashBoxesRouter from "./cash-boxes";
import bankAccountsRouter from "./bank-accounts";
import receiptVouchersRouter from "./receipt-vouchers";
import paymentVouchersRouter from "./payment-vouchers";
import cashTransfersRouter from "./cash-transfers";
import cashAnalyticsRouter from "./cash-analytics";
import aiRouter from "./ai";
import usersRouter from "./users";
import fiscalPeriodsRouter from "./fiscal-periods";
import costCentersRouter from "./cost-centers";
import employeesRouter from "./employees";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/admin", adminRouter);
router.use("/companies", companiesRouter);
router.use("/customers", customersRouter);
router.use("/suppliers", suppliersRouter);
router.use("/invoices", invoicesRouter);
router.use("/dashboard", dashboardRouter);
router.use("/reports", reportsRouter);
router.use("/inventory", inventoryRouter);
router.use("/accounts", accountsRouter);
router.use("/org", branchesRouter);
router.use("/journal-entries", journalEntriesRouter);
router.use("/currencies", currenciesRouter);
router.use("/accounting-reports", accountingReportsRouter);
router.use("/purchasing", purchasingRouter);
router.use("/sales", salesRouter);
router.use("/sales-analytics", salesAnalyticsRouter);
router.use("/purchases-analytics", purchasesAnalyticsRouter);
router.use("/cash-boxes",         cashBoxesRouter);
router.use("/bank-accounts",      bankAccountsRouter);
router.use("/receipt-vouchers",   receiptVouchersRouter);
router.use("/payment-vouchers",   paymentVouchersRouter);
router.use("/cash-transfers",     cashTransfersRouter);
router.use("/cash-analytics",     cashAnalyticsRouter);
router.use("/ai",                 aiRouter);
router.use("/users",              usersRouter);
router.use("/fiscal",             fiscalPeriodsRouter);
router.use("/cost-centers",       costCentersRouter);
router.use("/employees",          employeesRouter);
router.use(deviceInfoRouter);
router.use(zatcaRouter);

export default router;
