import { Router, type IRouter } from "express";
import healthRouter from "./health";
import companiesRouter from "./companies";
import customersRouter from "./customers";
import invoicesRouter from "./invoices";
import dashboardRouter from "./dashboard";
import deviceInfoRouter from "./device-info";
import zatcaRouter from "./zatca";
import authRouter from "./auth";
import superAdminAuthRouter from "./superAdminAuth";
import suppliersRouter from "./suppliers";
import adminRouter from "./admin";
import adminSeoRouter from "./admin-seo";
import seoRouter from "./seo";
import reportsRouter from "./reports";
import inventoryRouter from "./inventory";
import accountsRouter from "./accounts";
import branchesRouter from "./branches";
import journalEntriesRouter from "./journalEntries";
import trialBalancesRouter from "./trial-balances";
import currenciesRouter from "./currencies";
import accountingReportsRouter from "./reports-accounting";
import purchasingRouter from "./purchasing";
import goodsReceiptsRouter from "./goodsReceipts";
import goodsDeliveriesRouter from "./goodsDeliveries";
import salesRouter from "./sales";
import salesAnalyticsRouter from "./sales-analytics";
import purchasesAnalyticsRouter from "./purchases-analytics";
import cashBoxesRouter from "./cash-boxes";
import bankAccountsRouter from "./bank-accounts";
import receiptVouchersRouter from "./receipt-vouchers";
import paymentVouchersRouter from "./payment-vouchers";
import cashTransfersRouter from "./cash-transfers";
import cashAnalyticsRouter from "./cash-analytics";
import aiRouter from "./ai";
import usersRouter from "./users";
import fiscalPeriodsRouter from "./fiscal-periods";
import costCentersRouter from "./cost-centers";
import employeesRouter from "./employees";
import hrSettingsRouter from "./hr-settings";
import hrReportsRouter from "./hr-reports";
import storageRouter from "./storage";
import posSessionsRouter from "./pos-sessions";
import posTerminalsRouter from "./pos-terminals";
import notificationsRouter from "./notifications";
import supportMessagesRouter from "./support-messages";
import accountingMappingsRouter from "./accounting-mappings";
import backupRouter from "./backup";
import dataIoRouter from "./data-io";
import salesRepsRouter from "./sales-reps";
import auditLogRouter from "./audit-log";
import workSessionsRouter from "./work-sessions";
import workSessionSettingsRouter from "./work-session-settings";
import voiceAssistantRouter from "./voice-assistant";
import sessionsRouter from "./sessions";
import sequencesRouter from "./sequences";
import offersRouter from "./offers";
import adminModulesRouter from "./adminModules";
import adminIndustriesRouter from "./adminIndustries";
import productionRouter from "./production";
import faceAttendanceRouter from "./faceAttendance";
import securityEventsRouter from "./security-events";
import surveillanceDevicesRouter from "./surveillance-devices";
import inboxRouter from "./inbox";
import aiReportsRouter from "./ai-reports";
import dataDoctorRouter from "./data-doctor";
import contractingRouter from "./contracting";
import contractingAiRouter from "./contracting-ai";
import reportInvitationsRouter from "./report-invitations";
import realtimeRouter from "./realtime";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/auth/superadmin", superAdminAuthRouter);
// MUST be mounted BEFORE zatcaRouter (which is path-less and globally requires
// auth via requireAuthed). The SSE endpoint authenticates via ?token=… query
// param itself and would otherwise be 401-ed by zatca's middleware.
router.use("/realtime", realtimeRouter);
router.use("/reports-invitations", reportInvitationsRouter);
router.use("/admin/modules", adminModulesRouter);
router.use("/admin/industries", adminIndustriesRouter);
router.use("/admin/data-doctor", dataDoctorRouter);
router.use("/admin/seo", adminSeoRouter);
router.use("/admin", adminRouter);
router.use("/seo", seoRouter);
router.use("/companies", companiesRouter);
router.use("/customers", customersRouter);
router.use("/suppliers", suppliersRouter);
router.use("/invoices", invoicesRouter);
router.use("/dashboard", dashboardRouter);
router.use("/reports", reportsRouter);
router.use("/inventory", inventoryRouter);
router.use("/accounts", accountsRouter);
router.use("/org", branchesRouter);
router.use("/journal-entries", journalEntriesRouter);
router.use("/trial-balances", trialBalancesRouter);
router.use("/currencies", currenciesRouter);
router.use("/accounting-reports", accountingReportsRouter);
router.use("/purchasing", purchasingRouter);
router.use("/goods-receipts", goodsReceiptsRouter);
router.use("/goods-deliveries", goodsDeliveriesRouter);
router.use("/sales", salesRouter);
router.use("/sales-analytics", salesAnalyticsRouter);
router.use("/purchases-analytics", purchasesAnalyticsRouter);
router.use("/cash-boxes",         cashBoxesRouter);
router.use("/bank-accounts",      bankAccountsRouter);
router.use("/receipt-vouchers",   receiptVouchersRouter);
router.use("/payment-vouchers",   paymentVouchersRouter);
router.use("/cash-transfers",     cashTransfersRouter);
router.use("/cash-analytics",     cashAnalyticsRouter);
router.use("/ai",                 aiRouter);
router.use("/production",         productionRouter);
router.use("/users",              usersRouter);
router.use("/work-sessions",      workSessionsRouter);
router.use("/work-session-settings", workSessionSettingsRouter);
router.use("/voice-assistant",    voiceAssistantRouter);
router.use("/sessions",           sessionsRouter);
router.use("/fiscal",             fiscalPeriodsRouter);
router.use("/cost-centers",       costCentersRouter);
router.use("/employees",          employeesRouter);
router.use("/hr/settings",        hrSettingsRouter);
router.use("/hr/reports",         hrReportsRouter);
router.use("/hr/face",            faceAttendanceRouter);
router.use("/security-events",    securityEventsRouter);
router.use("/surveillance-devices", surveillanceDevicesRouter);
router.use(storageRouter);
router.use("/pos-sessions", posSessionsRouter);
router.use("/pos-terminals", posTerminalsRouter);
router.use("/notifications", notificationsRouter);
router.use("/inbox", inboxRouter);
router.use("/ai-reports", aiReportsRouter);
router.use("/support-messages", supportMessagesRouter);
router.use("/accounting-mappings", accountingMappingsRouter);
router.use("/backup", backupRouter);
router.use("/data-io", dataIoRouter);
router.use("/sales-reps", salesRepsRouter);
router.use("/audit-log", auditLogRouter);
router.use("/sequences", sequencesRouter);
router.use("/offers", offersRouter);
router.use(deviceInfoRouter);
router.use(zatcaRouter);
router.use("/contracting", contractingRouter);
router.use("/contracting-ai", contractingAiRouter);

export default router;
