// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pos-register/Aurora.tsx": () => import("../components/mockups/pos-register/Aurora.tsx"),
  "./components/mockups/pos-register/Onyx.tsx": () => import("../components/mockups/pos-register/Onyx.tsx")
};
