// World countries master list for the customer form + invoice printing.
//
// This is intentionally SEPARATE from `countries.ts` (the company-registration
// catalogue) so the customer-facing country picker can offer the full set of
// ISO 3166-1 countries without bloating the registration list. Each entry
// carries the ISO alpha-2 code plus Arabic and English display names.
//
// `getWorldCountryName(code, lang)` resolves a stored code (e.g. "SA") to a
// localized display name, falling back to the raw code when unknown.

export interface WorldCountry {
  /** ISO 3166-1 alpha-2 code (uppercase), e.g. "SA". Stored on the customer. */
  code: string;
  nameAr: string;
  nameEn: string;
}

export const WORLD_COUNTRIES: readonly WorldCountry[] = [
  { code: "SA", nameAr: "المملكة العربية السعودية", nameEn: "Saudi Arabia" },
  { code: "AE", nameAr: "الإمارات العربية المتحدة", nameEn: "United Arab Emirates" },
  { code: "BH", nameAr: "البحرين", nameEn: "Bahrain" },
  { code: "KW", nameAr: "الكويت", nameEn: "Kuwait" },
  { code: "OM", nameAr: "عُمان", nameEn: "Oman" },
  { code: "QA", nameAr: "قطر", nameEn: "Qatar" },
  { code: "YE", nameAr: "اليمن", nameEn: "Yemen" },
  { code: "JO", nameAr: "الأردن", nameEn: "Jordan" },
  { code: "SY", nameAr: "سوريا", nameEn: "Syria" },
  { code: "LB", nameAr: "لبنان", nameEn: "Lebanon" },
  { code: "IQ", nameAr: "العراق", nameEn: "Iraq" },
  { code: "PS", nameAr: "فلسطين", nameEn: "Palestine" },
  { code: "EG", nameAr: "مصر", nameEn: "Egypt" },
  { code: "SD", nameAr: "السودان", nameEn: "Sudan" },
  { code: "LY", nameAr: "ليبيا", nameEn: "Libya" },
  { code: "TN", nameAr: "تونس", nameEn: "Tunisia" },
  { code: "DZ", nameAr: "الجزائر", nameEn: "Algeria" },
  { code: "MA", nameAr: "المغرب", nameEn: "Morocco" },
  { code: "MR", nameAr: "موريتانيا", nameEn: "Mauritania" },
  { code: "SO", nameAr: "الصومال", nameEn: "Somalia" },
  { code: "DJ", nameAr: "جيبوتي", nameEn: "Djibouti" },
  { code: "KM", nameAr: "جزر القمر", nameEn: "Comoros" },
  { code: "AF", nameAr: "أفغانستان", nameEn: "Afghanistan" },
  { code: "AL", nameAr: "ألبانيا", nameEn: "Albania" },
  { code: "AD", nameAr: "أندورا", nameEn: "Andorra" },
  { code: "AO", nameAr: "أنغولا", nameEn: "Angola" },
  { code: "AG", nameAr: "أنتيغوا وباربودا", nameEn: "Antigua and Barbuda" },
  { code: "AR", nameAr: "الأرجنتين", nameEn: "Argentina" },
  { code: "AM", nameAr: "أرمينيا", nameEn: "Armenia" },
  { code: "AU", nameAr: "أستراليا", nameEn: "Australia" },
  { code: "AT", nameAr: "النمسا", nameEn: "Austria" },
  { code: "AZ", nameAr: "أذربيجان", nameEn: "Azerbaijan" },
  { code: "BS", nameAr: "الباهاما", nameEn: "Bahamas" },
  { code: "BD", nameAr: "بنغلاديش", nameEn: "Bangladesh" },
  { code: "BB", nameAr: "بربادوس", nameEn: "Barbados" },
  { code: "BY", nameAr: "بيلاروسيا", nameEn: "Belarus" },
  { code: "BE", nameAr: "بلجيكا", nameEn: "Belgium" },
  { code: "BZ", nameAr: "بليز", nameEn: "Belize" },
  { code: "BJ", nameAr: "بنين", nameEn: "Benin" },
  { code: "BT", nameAr: "بوتان", nameEn: "Bhutan" },
  { code: "BO", nameAr: "بوليفيا", nameEn: "Bolivia" },
  { code: "BA", nameAr: "البوسنة والهرسك", nameEn: "Bosnia and Herzegovina" },
  { code: "BW", nameAr: "بوتسوانا", nameEn: "Botswana" },
  { code: "BR", nameAr: "البرازيل", nameEn: "Brazil" },
  { code: "BN", nameAr: "بروناي", nameEn: "Brunei" },
  { code: "BG", nameAr: "بلغاريا", nameEn: "Bulgaria" },
  { code: "BF", nameAr: "بوركينا فاسو", nameEn: "Burkina Faso" },
  { code: "BI", nameAr: "بوروندي", nameEn: "Burundi" },
  { code: "CV", nameAr: "الرأس الأخضر", nameEn: "Cape Verde" },
  { code: "KH", nameAr: "كمبوديا", nameEn: "Cambodia" },
  { code: "CM", nameAr: "الكاميرون", nameEn: "Cameroon" },
  { code: "CA", nameAr: "كندا", nameEn: "Canada" },
  { code: "CF", nameAr: "جمهورية أفريقيا الوسطى", nameEn: "Central African Republic" },
  { code: "TD", nameAr: "تشاد", nameEn: "Chad" },
  { code: "CL", nameAr: "تشيلي", nameEn: "Chile" },
  { code: "CN", nameAr: "الصين", nameEn: "China" },
  { code: "CO", nameAr: "كولومبيا", nameEn: "Colombia" },
  { code: "CG", nameAr: "الكونغو", nameEn: "Congo" },
  { code: "CD", nameAr: "جمهورية الكونغو الديمقراطية", nameEn: "DR Congo" },
  { code: "CR", nameAr: "كوستاريكا", nameEn: "Costa Rica" },
  { code: "CI", nameAr: "ساحل العاج", nameEn: "Côte d'Ivoire" },
  { code: "HR", nameAr: "كرواتيا", nameEn: "Croatia" },
  { code: "CU", nameAr: "كوبا", nameEn: "Cuba" },
  { code: "CY", nameAr: "قبرص", nameEn: "Cyprus" },
  { code: "CZ", nameAr: "التشيك", nameEn: "Czechia" },
  { code: "DK", nameAr: "الدنمارك", nameEn: "Denmark" },
  { code: "DM", nameAr: "دومينيكا", nameEn: "Dominica" },
  { code: "DO", nameAr: "جمهورية الدومينيكان", nameEn: "Dominican Republic" },
  { code: "EC", nameAr: "الإكوادور", nameEn: "Ecuador" },
  { code: "SV", nameAr: "السلفادور", nameEn: "El Salvador" },
  { code: "GQ", nameAr: "غينيا الاستوائية", nameEn: "Equatorial Guinea" },
  { code: "ER", nameAr: "إريتريا", nameEn: "Eritrea" },
  { code: "EE", nameAr: "إستونيا", nameEn: "Estonia" },
  { code: "SZ", nameAr: "إسواتيني", nameEn: "Eswatini" },
  { code: "ET", nameAr: "إثيوبيا", nameEn: "Ethiopia" },
  { code: "FJ", nameAr: "فيجي", nameEn: "Fiji" },
  { code: "FI", nameAr: "فنلندا", nameEn: "Finland" },
  { code: "FR", nameAr: "فرنسا", nameEn: "France" },
  { code: "GA", nameAr: "الغابون", nameEn: "Gabon" },
  { code: "GM", nameAr: "غامبيا", nameEn: "Gambia" },
  { code: "GE", nameAr: "جورجيا", nameEn: "Georgia" },
  { code: "DE", nameAr: "ألمانيا", nameEn: "Germany" },
  { code: "GH", nameAr: "غانا", nameEn: "Ghana" },
  { code: "GR", nameAr: "اليونان", nameEn: "Greece" },
  { code: "GD", nameAr: "غرينادا", nameEn: "Grenada" },
  { code: "GT", nameAr: "غواتيمالا", nameEn: "Guatemala" },
  { code: "GN", nameAr: "غينيا", nameEn: "Guinea" },
  { code: "GW", nameAr: "غينيا بيساو", nameEn: "Guinea-Bissau" },
  { code: "GY", nameAr: "غيانا", nameEn: "Guyana" },
  { code: "HT", nameAr: "هايتي", nameEn: "Haiti" },
  { code: "HN", nameAr: "هندوراس", nameEn: "Honduras" },
  { code: "HU", nameAr: "المجر", nameEn: "Hungary" },
  { code: "IS", nameAr: "آيسلندا", nameEn: "Iceland" },
  { code: "IN", nameAr: "الهند", nameEn: "India" },
  { code: "ID", nameAr: "إندونيسيا", nameEn: "Indonesia" },
  { code: "IR", nameAr: "إيران", nameEn: "Iran" },
  { code: "IE", nameAr: "أيرلندا", nameEn: "Ireland" },
  { code: "IT", nameAr: "إيطاليا", nameEn: "Italy" },
  { code: "JM", nameAr: "جامايكا", nameEn: "Jamaica" },
  { code: "JP", nameAr: "اليابان", nameEn: "Japan" },
  { code: "KZ", nameAr: "كازاخستان", nameEn: "Kazakhstan" },
  { code: "KE", nameAr: "كينيا", nameEn: "Kenya" },
  { code: "KI", nameAr: "كيريباتي", nameEn: "Kiribati" },
  { code: "KP", nameAr: "كوريا الشمالية", nameEn: "North Korea" },
  { code: "KR", nameAr: "كوريا الجنوبية", nameEn: "South Korea" },
  { code: "KG", nameAr: "قيرغيزستان", nameEn: "Kyrgyzstan" },
  { code: "LA", nameAr: "لاوس", nameEn: "Laos" },
  { code: "LV", nameAr: "لاتفيا", nameEn: "Latvia" },
  { code: "LS", nameAr: "ليسوتو", nameEn: "Lesotho" },
  { code: "LR", nameAr: "ليبيريا", nameEn: "Liberia" },
  { code: "LI", nameAr: "ليختنشتاين", nameEn: "Liechtenstein" },
  { code: "LT", nameAr: "ليتوانيا", nameEn: "Lithuania" },
  { code: "LU", nameAr: "لوكسمبورغ", nameEn: "Luxembourg" },
  { code: "MG", nameAr: "مدغشقر", nameEn: "Madagascar" },
  { code: "MW", nameAr: "مالاوي", nameEn: "Malawi" },
  { code: "MY", nameAr: "ماليزيا", nameEn: "Malaysia" },
  { code: "MV", nameAr: "المالديف", nameEn: "Maldives" },
  { code: "ML", nameAr: "مالي", nameEn: "Mali" },
  { code: "MT", nameAr: "مالطا", nameEn: "Malta" },
  { code: "MH", nameAr: "جزر مارشال", nameEn: "Marshall Islands" },
  { code: "MU", nameAr: "موريشيوس", nameEn: "Mauritius" },
  { code: "MX", nameAr: "المكسيك", nameEn: "Mexico" },
  { code: "FM", nameAr: "ميكرونيزيا", nameEn: "Micronesia" },
  { code: "MD", nameAr: "مولدوفا", nameEn: "Moldova" },
  { code: "MC", nameAr: "موناكو", nameEn: "Monaco" },
  { code: "MN", nameAr: "منغوليا", nameEn: "Mongolia" },
  { code: "ME", nameAr: "الجبل الأسود", nameEn: "Montenegro" },
  { code: "MZ", nameAr: "موزمبيق", nameEn: "Mozambique" },
  { code: "MM", nameAr: "ميانمار", nameEn: "Myanmar" },
  { code: "NA", nameAr: "ناميبيا", nameEn: "Namibia" },
  { code: "NR", nameAr: "ناورو", nameEn: "Nauru" },
  { code: "NP", nameAr: "نيبال", nameEn: "Nepal" },
  { code: "NL", nameAr: "هولندا", nameEn: "Netherlands" },
  { code: "NZ", nameAr: "نيوزيلندا", nameEn: "New Zealand" },
  { code: "NI", nameAr: "نيكاراغوا", nameEn: "Nicaragua" },
  { code: "NE", nameAr: "النيجر", nameEn: "Niger" },
  { code: "NG", nameAr: "نيجيريا", nameEn: "Nigeria" },
  { code: "MK", nameAr: "مقدونيا الشمالية", nameEn: "North Macedonia" },
  { code: "NO", nameAr: "النرويج", nameEn: "Norway" },
  { code: "PK", nameAr: "باكستان", nameEn: "Pakistan" },
  { code: "PW", nameAr: "بالاو", nameEn: "Palau" },
  { code: "PA", nameAr: "بنما", nameEn: "Panama" },
  { code: "PG", nameAr: "بابوا غينيا الجديدة", nameEn: "Papua New Guinea" },
  { code: "PY", nameAr: "باراغواي", nameEn: "Paraguay" },
  { code: "PE", nameAr: "بيرو", nameEn: "Peru" },
  { code: "PH", nameAr: "الفلبين", nameEn: "Philippines" },
  { code: "PL", nameAr: "بولندا", nameEn: "Poland" },
  { code: "PT", nameAr: "البرتغال", nameEn: "Portugal" },
  { code: "RO", nameAr: "رومانيا", nameEn: "Romania" },
  { code: "RU", nameAr: "روسيا", nameEn: "Russia" },
  { code: "RW", nameAr: "رواندا", nameEn: "Rwanda" },
  { code: "KN", nameAr: "سانت كيتس ونيفيس", nameEn: "Saint Kitts and Nevis" },
  { code: "LC", nameAr: "سانت لوسيا", nameEn: "Saint Lucia" },
  { code: "VC", nameAr: "سانت فنسنت والغرينادين", nameEn: "Saint Vincent and the Grenadines" },
  { code: "WS", nameAr: "ساموا", nameEn: "Samoa" },
  { code: "SM", nameAr: "سان مارينو", nameEn: "San Marino" },
  { code: "ST", nameAr: "ساو تومي وبرينسيب", nameEn: "São Tomé and Príncipe" },
  { code: "SN", nameAr: "السنغال", nameEn: "Senegal" },
  { code: "RS", nameAr: "صربيا", nameEn: "Serbia" },
  { code: "SC", nameAr: "سيشل", nameEn: "Seychelles" },
  { code: "SL", nameAr: "سيراليون", nameEn: "Sierra Leone" },
  { code: "SG", nameAr: "سنغافورة", nameEn: "Singapore" },
  { code: "SK", nameAr: "سلوفاكيا", nameEn: "Slovakia" },
  { code: "SI", nameAr: "سلوفينيا", nameEn: "Slovenia" },
  { code: "SB", nameAr: "جزر سليمان", nameEn: "Solomon Islands" },
  { code: "ZA", nameAr: "جنوب أفريقيا", nameEn: "South Africa" },
  { code: "SS", nameAr: "جنوب السودان", nameEn: "South Sudan" },
  { code: "ES", nameAr: "إسبانيا", nameEn: "Spain" },
  { code: "LK", nameAr: "سريلانكا", nameEn: "Sri Lanka" },
  { code: "SR", nameAr: "سورينام", nameEn: "Suriname" },
  { code: "SE", nameAr: "السويد", nameEn: "Sweden" },
  { code: "CH", nameAr: "سويسرا", nameEn: "Switzerland" },
  { code: "TW", nameAr: "تايوان", nameEn: "Taiwan" },
  { code: "TJ", nameAr: "طاجيكستان", nameEn: "Tajikistan" },
  { code: "TZ", nameAr: "تنزانيا", nameEn: "Tanzania" },
  { code: "TH", nameAr: "تايلاند", nameEn: "Thailand" },
  { code: "TL", nameAr: "تيمور الشرقية", nameEn: "Timor-Leste" },
  { code: "TG", nameAr: "توغو", nameEn: "Togo" },
  { code: "TO", nameAr: "تونغا", nameEn: "Tonga" },
  { code: "TT", nameAr: "ترينيداد وتوباغو", nameEn: "Trinidad and Tobago" },
  { code: "TR", nameAr: "تركيا", nameEn: "Turkey" },
  { code: "TM", nameAr: "تركمانستان", nameEn: "Turkmenistan" },
  { code: "TV", nameAr: "توفالو", nameEn: "Tuvalu" },
  { code: "UG", nameAr: "أوغندا", nameEn: "Uganda" },
  { code: "UA", nameAr: "أوكرانيا", nameEn: "Ukraine" },
  { code: "GB", nameAr: "المملكة المتحدة", nameEn: "United Kingdom" },
  { code: "US", nameAr: "الولايات المتحدة", nameEn: "United States" },
  { code: "UY", nameAr: "أوروغواي", nameEn: "Uruguay" },
  { code: "UZ", nameAr: "أوزبكستان", nameEn: "Uzbekistan" },
  { code: "VU", nameAr: "فانواتو", nameEn: "Vanuatu" },
  { code: "VA", nameAr: "الفاتيكان", nameEn: "Vatican City" },
  { code: "VE", nameAr: "فنزويلا", nameEn: "Venezuela" },
  { code: "VN", nameAr: "فيتنام", nameEn: "Vietnam" },
  { code: "ZM", nameAr: "زامبيا", nameEn: "Zambia" },
  { code: "ZW", nameAr: "زيمبابوي", nameEn: "Zimbabwe" },
  { code: "HK", nameAr: "هونغ كونغ", nameEn: "Hong Kong" },
  { code: "MO", nameAr: "ماكاو", nameEn: "Macao" },
] as const;

const BY_CODE: Record<string, WorldCountry> = WORLD_COUNTRIES.reduce(
  (acc, c) => { acc[c.code] = c; return acc; },
  {} as Record<string, WorldCountry>,
);

/**
 * Resolve an ISO alpha-2 country code to its localized display name. Falls back
 * to the raw (uppercased) code when the country is not in the catalogue so the
 * caller never renders an empty string.
 */
export function getWorldCountryName(
  code: string | null | undefined,
  lang: "ar" | "en" = "ar",
): string {
  const key = String(code ?? "").trim().toUpperCase();
  if (!key) return "";
  const found = BY_CODE[key];
  if (!found) return key;
  return lang === "en" ? found.nameEn : found.nameAr;
}
