import { pgTable, serial, text, integer, date, timestamp, decimal, boolean, unique } from "drizzle-orm/pg-core";
import { companiesTable } from "./companies";
import { branchesTable } from "./branches";
import { accountsTable } from "./accounts";

export const employeesTable = pgTable("employees", {
  id:             serial("id").primaryKey(),
  companyId:      integer("company_id").references(() => companiesTable.id).notNull(),
  branchId:       integer("branch_id").references(() => branchesTable.id),
  code:           text("code").notNull(),
  nameAr:         text("name_ar").notNull(),
  nameEn:         text("name_en"),
  idType:         text("id_type").notNull().default("iqama"),
  idNumber:       text("id_number"),
  iqamaExpiry:    date("iqama_expiry"),
  passportNumber: text("passport_number"),
  passportExpiry: date("passport_expiry"),
  nationality:    text("nationality"),
  gender:         text("gender"),
  birthDate:      date("birth_date"),
  mobile:         text("mobile"),
  email:          text("email"),
  hireDate:       date("hire_date"),
  endDate:        date("end_date"),
  department:     text("department"),
  jobTitle:       text("job_title"),
  sponsor:        text("sponsor"),
  profession:     text("profession"),
  status:         text("status").notNull().default("active"),
  basicSalary:    decimal("basic_salary", { precision: 12, scale: 2 }).default("0"),
  housingAllow:   decimal("housing_allow", { precision: 12, scale: 2 }).default("0"),
  transportAllow: decimal("transport_allow", { precision: 12, scale: 2 }).default("0"),
  otherAllow:     decimal("other_allow", { precision: 12, scale: 2 }).default("0"),
  bankAccountIban:text("bank_account_iban"),
  bankName:       text("bank_name"),
  payableAccountId:integer("payable_account_id").references(() => accountsTable.id),
  photoUrl:       text("photo_url"),
  notes:          text("notes"),
  createdAt:      timestamp("created_at").defaultNow().notNull(),
  updatedAt:      timestamp("updated_at").defaultNow().notNull(),
}, (t) => ({
  uqIdNumber: unique("uq_employees_company_idnumber").on(t.companyId, t.idNumber),
  uqCode:     unique("uq_employees_company_code").on(t.companyId, t.code),
}));

export const employeeContractsTable = pgTable("employee_contracts", {
  id:             serial("id").primaryKey(),
  companyId:      integer("company_id").references(() => companiesTable.id).notNull(),
  employeeId:     integer("employee_id").references(() => employeesTable.id, { onDelete: "cascade" }).notNull(),
  contractNumber: text("contract_number").notNull(),
  contractType:   text("contract_type").notNull().default("fixed"),
  startDate:      date("start_date").notNull(),
  endDate:        date("end_date"),
  basicSalary:    decimal("basic_salary", { precision: 12, scale: 2 }).notNull().default("0"),
  housingAllow:   decimal("housing_allow", { precision: 12, scale: 2 }).default("0"),
  transportAllow: decimal("transport_allow", { precision: 12, scale: 2 }).default("0"),
  otherAllow:     decimal("other_allow", { precision: 12, scale: 2 }).default("0"),
  workingHours:   integer("working_hours").default(8),
  probationDays:  integer("probation_days").default(90),
  noticePeriod:   integer("notice_period_days").default(60),
  vacationDays:   integer("vacation_days").default(21),
  terms:          text("terms"),
  status:         text("status").notNull().default("active"),
  renewedFromId:  integer("renewed_from_id"),
  notes:          text("notes"),
  createdAt:      timestamp("created_at").defaultNow().notNull(),
  updatedAt:      timestamp("updated_at").defaultNow().notNull(),
});

export const employeeLeavesTable = pgTable("employee_leaves", {
  id:           serial("id").primaryKey(),
  companyId:    integer("company_id").references(() => companiesTable.id).notNull(),
  employeeId:   integer("employee_id").references(() => employeesTable.id, { onDelete: "cascade" }).notNull(),
  leaveType:    text("leave_type").notNull(),
  startDate:    date("start_date").notNull(),
  endDate:      date("end_date").notNull(),
  days:         integer("days").notNull().default(1),
  paid:         boolean("paid").notNull().default(true),
  status:       text("status").notNull().default("pending"),
  reason:       text("reason"),
  approvedBy:   text("approved_by"),
  approvedAt:   timestamp("approved_at"),
  createdAt:    timestamp("created_at").defaultNow().notNull(),
  updatedAt:    timestamp("updated_at").defaultNow().notNull(),
});
