import { pgTable, serial, integer, varchar, text, timestamp, index, numeric, jsonb } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// Where the event came from. AI = generated by an analytics rule;
// camera = manual flag from a stream review; user = entered by an operator;
// erp = derived from another ERP signal (HR absence, production halt …).
export const SECURITY_EVENT_SOURCES = ["camera", "ai", "user", "erp"] as const;

// Which ERP module this event is tied to (if any). Drives the reports
// and the action dispatcher (HR violation, production task, …).
export const SECURITY_LINKED_MODULES = [
  "hr", "production", "inventory", "branch", "none",
] as const;

export const SECURITY_EVENT_TYPES = [
  "intrusion",
  "theft",
  "suspicious_movement",
  "unknown_person",
  "after_hours_presence",
  "missing_item",
  "unusual_gathering",
  "tampering",
  "other",
] as const;

export const SECURITY_EVENT_SEVERITIES = ["low", "medium", "high", "critical"] as const;

export const SECURITY_EVENT_STATUSES = [
  "open",
  "investigating",
  "closed",
  "false_positive",
] as const;

export const securityEventsTable = pgTable("security_events", {
  id: serial("id").primaryKey(),
  companyId: integer("company_id").notNull(),
  branchId: integer("branch_id"),
  cameraLabel: varchar("camera_label", { length: 200 }),
  eventType: varchar("event_type", { length: 50 }).notNull(),
  severity: varchar("severity", { length: 20 }).notNull().default("medium"),
  title: varchar("title", { length: 300 }).notNull(),
  description: text("description"),
  imageUrl: text("image_url"),
  videoClipUrl: text("video_clip_url"),
  // 0.0000 - 1.0000 — confidence score from AI (manual events leave it null)
  confidence: numeric("confidence", { precision: 5, scale: 4 }),
  eventDateTime: timestamp("event_date_time", { withTimezone: false }).notNull().defaultNow(),
  status: varchar("status", { length: 20 }).notNull().default("open"),
  assignedToUserId: integer("assigned_to_user_id"),
  createdByUserId: integer("created_by_user_id"),
  resolvedAt: timestamp("resolved_at", { withTimezone: false }),
  resolutionNote: text("resolution_note"),

  // ── AI / ERP integration ─────────────────────────────────────────
  // Origin of the event row.
  source: varchar("source", { length: 20 }).notNull().default("user"),
  // Optional FK to surveillance_devices.id (the actual camera).
  cameraId: integer("camera_id"),
  // Which ERP module this event belongs to (drives reports + actions).
  linkedModule: varchar("linked_module", { length: 20 }).notNull().default("none"),
  // Generic foreign reference inside that module (e.g. the violation id).
  refId: integer("ref_id"),
  // Direct cross-references kept separately so reports can JOIN cleanly
  // even when a single event touches more than one module (e.g. HR + Inventory).
  employeeId: integer("employee_id"),
  productionLineId: integer("production_line_id"),
  warehouseId: integer("warehouse_id"),
  departmentId: integer("department_id"),
  // Raw AI analysis output (labels, bounding boxes, suggested action…).
  aiResult: jsonb("ai_result"),
  // Audit trail of automatic actions executed for this event.
  // [{ kind: "alert"|"task"|"violation", refId?, status, at, note? }]
  actionsTaken: jsonb("actions_taken"),

  createdAt: timestamp("created_at", { withTimezone: false }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: false }).notNull().default(sql`now()`),
}, (t) => ({
  byCompanyDate: index("security_events_company_date_idx").on(t.companyId, t.eventDateTime),
  byCompanyStatus: index("security_events_company_status_idx").on(t.companyId, t.status),
  byCompanySeverity: index("security_events_company_severity_idx").on(t.companyId, t.severity),
  byCompanyModule: index("security_events_company_module_idx").on(t.companyId, t.linkedModule),
  byCompanyCamera: index("security_events_company_camera_idx").on(t.companyId, t.cameraId),
}));

export type SecurityEventRow = typeof securityEventsTable.$inferSelect;
export type SecurityEventInsert = typeof securityEventsTable.$inferInsert;
